# File: backend/app/infrastructure/mail/meta_report_template.py
"""Observed report-email content; this does not certify account, DOM or correlation."""
from app.infrastructure.mail.meta_otp_parser import MetaOtpParser, TemplateEvidence


META_REPORT_TEMPLATE_VERSION = "meta-report-email-v1"

# Whole-message anchoring also rejects extra or repeated confirmation-code zones.
# Whitespace includes HTML block separators, wrapped lines and nonbreaking spaces.
# Preamble supports optional header text and image/alt tags generated by mail clients.
# Postamble supports optional mailto format in recipients, trailing postal zip, and tracking links.
_CODE_PATTERN = (
    r"\A\s*"
    r"(?:(?:Email\s+confirmation\s+code|\[[^\]\r\n]+\])\s*)*"
    r"Hi,\s+"
    r"We\s+noticed\s+you\s+are\s+trying\s+to\s+submit\s+a\s+report\s+to\s+Meta\s+"
    r"from\s+your\s+email\s+address\.\s+"
    r"To\s+confirm\s+it's\s+you,\s+please\s+enter\s+the\s+confirmation\s+code\s+"
    r"below\s+to\s+verify\s+your\s+email\s+address\.\s+"
    r"(?P<code>[0-9]{6})\s+"
    r"This\s+confirmation\s+code\s+will\s+be\s+valid\s+for\s+1\s+hour\.\s+"
    r"Thank\s+you,\s+Meta\s+Support"
    r"(?:\s+This\s+message\s+was\s+sent\s+to\s+\S+?\s+at\s+your\s+request\.)?"
    r"(?:\s+Meta\s+Platforms,\s+Inc\.,\s+Attention:\s+Community\s+Support,\s+"
    r"1\s+Meta\s+Way,\s+Menlo\s+Park,\s+CA\s+94025\.?)?"
    r"(?:\s*\[[^\]\r\n]+\])*"
    r"\s*\Z"
)


def meta_report_template_evidence() -> TemplateEvidence:
    """Return the explicit content profile transcribed from the supplied PDF."""
    return TemplateEvidence(
        version=META_REPORT_TEMPLATE_VERSION,
        sender_addresses=("notification@email.meta.com",),
        subject_pattern=r"\s*Please verify your email address\s*",
        code_pattern=_CODE_PATTERN,
        code_length=6,
        request_id_pattern=None,
        evidence_reference="User-provided Meta report verification email PDF, 2026-10-06",
    )


def meta_report_template_profiles() -> dict[str, TemplateEvidence]:
    profile = meta_report_template_evidence()
    return {profile.version: profile}


def create_meta_report_otp_parser() -> MetaOtpParser:
    return MetaOtpParser(meta_report_template_profiles())
